# Generated by Django 3.0.4 on 2020-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancestatus',
            name='status',
            field=models.IntegerField(),
        ),
    ]
