# Generated by Django 3.0.4 on 2020-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200310_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliancestatus',
            options={'verbose_name_plural': 'Appliance Status'},
        ),
        migrations.AlterField(
            model_name='appliancestatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0),
        ),
    ]
