# Generated by Django 3.0.5 on 2020-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200311_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliancestatus',
            old_name='status',
            new_name='Fan',
        ),
        migrations.AddField(
            model_name='appliancestatus',
            name='light',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliancestatus',
            name='motor',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliancestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
