# Generated by Django 3.0.5 on 2020-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200415_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliancestatus',
            name='appliance',
        ),
    ]
