# Generated by Django 3.0.5 on 2020-04-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_appliancestatus_appliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliancestatus',
            old_name='id',
            new_name='user_id',
        ),
    ]
