# Generated by Django 3.0.5 on 2020-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200415_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliancestatus',
            old_name='Fan',
            new_name='fan',
        ),
        migrations.AlterField(
            model_name='appliancestatus',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
