# Generated by Django 3.0.5 on 2020-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_appliancestatus_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancestatus',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
